# Generated by Django 3.2 on 2021-04-24 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0004_product_instences'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product_instences',
            options={'verbose_name_plural': 'Product Instences'},
        ),
    ]
